-- Exploratory Data Analysis

-- 1. View all Data

SELECT * FROM SolarPanelMetrics

-- 2. Count of Panels

SELECT
	COUNT(*) [CountOfPanels]
FROM SolarPanelMetrics

-- 3. Checking Distinct Models

SELECT DISTINCT [model_name]
FROM SolarPanelMetrics

-- 4. Highest Producing Panel

SELECT *
FROM(
	SELECT
		*,
		ROW_NUMBER() OVER(ORDER BY energy_output_kwh DESC) [Highest Panel] 
	FROM SolarPanelMetrics
)t WHERE [Highest Panel] = 1

-- 5. Average Efficiency Rating

SELECT
	CAST(ROUND(AVG(efficiency_rating), 2) AS FLOAT) [Average Efficiency]
FROM SolarPanelMetrics

--6. Minimum and maximum energy_output_kwh recorded.

SELECT *
FROM(
	SELECT
		*,
		MIN(energy_output_kwh) OVER() [Min Energy Output],
		MAX(energy_output_kwh) OVER() [Max Energy Output]
	FROM SolarPanelMetrics
)t WHERE energy_output_kwh = [Min Energy Output]
	OR energy_output_kwh = [Max Energy Output]

-- 7. Earliest and latest last_maintenance_date.

SELECT *
FROM(
	SELECT
		*,
		MIN(last_maintenance_date) OVER() [Earliest Maintenance],
		MAX(last_maintenance_date) OVER() [Latest_Maintenance]
	FROM SolarPanelMetrics
)t WHERE last_maintenance_date = [Earliest Maintenance]
	OR last_maintenance_date = Latest_Maintenance

-- 8. Median efficiency_rating for the entire dataset.
 
SELECT DISTINCT
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY efficiency_rating) OVER () [Median Value]
FROM SolarPanelMetrics

-- 9. Check for null in the efficiency_rating column.

SELECT *
FROM SolarPanelMetrics
WHERE efficiency_rating IS NULL

-- 10. Find the top 3 most common model_name variants.

SELECT TOP 3
	[model_name],
	COUNT([model_name]) [Common Model Name]
FROM SolarPanelMetrics
GROUP BY [model_name]
ORDER BY COUNT([model_name]) DESC

-- 11. Determine the average energy_output_kwh per model.

SELECT
	[model_name],
	CAST(ROUND(AVG(energy_output_kwh), 2) AS FLOAT) [AvgEnergy By Model]
FROM SolarPanelMetrics
GROUP BY [model_name]

-- 12. Check for potential outliers in energy_output_kwh

SELECT *
FROM (
    SELECT
        *,
        AVG(energy_output_kwh) OVER () [Mean_value],
        STDEV(energy_output_kwh) OVER () [Std_value]
    FROM SolarPanelMetrics
) t
WHERE ABS(energy_output_kwh - Mean_value) > 3 * Std_value

-- 13. Summarize the total energy generated by all panels combined.

SELECT
	SUM(energy_output_kwh) [Total Energy]
FROM SolarPanelMetrics

-- 14. Identify the date range spread of maintenance activities.

SELECT
	DATEDIFF(MONTH, MIN(last_maintenance_date), MAX(last_maintenance_date)) [Date Range]
FROM SolarPanelMetrics

-- 15. Count the number of unique panel_id records to ensure data integrity.

SELECT DISTINCT	
	COUNT(panel_id) [Unique Panel_id]
FROM SolarPanelMetrics

-- 16. Calculate the average efficiency for each unique model_name.

SELECT
	[model_name],
	CAST(ROUND(AVG(efficiency_rating), 2) AS FLOAT) [Avg Efficiency By Panel]
FROM SolarPanelMetrics
GROUP BY [model_name]

-- 17. Identify the percentage of total fleet represented by each model.

SELECT
	[model_name],
	COUNT(*) [Model Count],
	CAST(COUNT(*) * 100 / SUM(COUNT(*)) OVER() AS DECIMAL(10,2)) [Percentage of Fleet]
FROM SolarPanelMetrics
GROUP BY [model_name]

-- 18. Find panels that have an energy_output_kwh below a specific baseline.

SELECT *
FROM(
	SELECT
		*,
		CAST(ROUND(AVG(energy_output_kwh) OVER(), 2) AS FLOAT) [Avg Energy Output]
	FROM SolarPanelMetrics
)t WHERE energy_output_kwh < [Avg Energy Output]

-- 19. Group panels by year of last maintenance to see maintenance density.

SELECT
	[model_name],
	DATEPART(YEAR, last_maintenance_date) [Year of maintenance]
FROM SolarPanelMetrics
GROUP BY [model_name], DATEPART(YEAR, last_maintenance_date)

-- 20. Create a summary table grouping by model_name showing count, avg efficiency, and total output.

SELECT
	[model_name],
	COUNT(*) [Total Count],
	CAST(ROUND(AVG(efficiency_rating), 2) AS FLOAT) [Avg Efficiency],
	SUM(energy_output_kwh) [Total Output]
FROM SolarPanelMetrics
GROUP BY [model_name]

-- PERFORMANCE & KPI Analysis

-- 1. Rank solar panels by highest energy output

SELECT
	panel_id,
	[model_name],
	energy_output_kwh,
	RANK() OVER(ORDER BY energy_output_kwh DESC) HighestEnergy
FROM SolarPanelMetrics

-- 2. Identify the top 5 best-performing panel models

SELECT *
FROM(
	SELECT
		panel_id,
		[model_name],
		efficiency_rating,
		DENSE_RANK() OVER(ORDER BY efficiency_rating) BestPerformingModels
	FROM SolarPanelMetrics
)t WHERE BestPerformingModels <= 5

-- 3. Find the lowest-performing panels in each model category

SELECT *
FROM (
	SELECT
		panel_id,
		[model_name],
		efficiency_rating,
		DENSE_RANK() OVER(PARTITION BY [model_name] ORDER BY efficiency_rating) LowestPerformingModels
	FROM SolarPanelMetrics
)t WHERE LowestPerformingModels <= 5

-- 4. Compare each panel’s output with the overall average output

SELECT
	panel_id,
	[model_name],
	energy_output_kwh,
	CAST(ROUND(AVG(energy_output_kwh) OVER(), 2) AS DECIMAL(10,2)) OverallAVGOutput,
	energy_output_kwh - CAST(ROUND(AVG(energy_output_kwh) OVER(), 2) AS DECIMAL(10,2)) DiffAVG,
	CASE 
		WHEN energy_output_kwh - CAST(ROUND(AVG(energy_output_kwh) OVER(), 2) AS DECIMAL(10,2)) > 0 THEN 'Above Average'
		WHEN energy_output_kwh - CAST(ROUND(AVG(energy_output_kwh) OVER(), 2) AS DECIMAL(10,2)) < 0 THEN 'Below Average'
		ELSE 'Equal to Average'
	END Performance_status
FROM SolarPanelMetrics

-- 5. Calculate running total of energy generated over time

SELECT
	panel_id,
	[model_name],
	last_maintenance_date,
	energy_output_kwh,
	SUM(energy_output_kwh) OVER(ORDER BY last_maintenance_date) RunningTotalEnergy
FROM SolarPanelMetrics

-- 6. Find month-over-month growth in energy production

SELECT
	MONTH(last_maintenance_date) MonthOfMaintenance,
	SUM(energy_output_kwh) EnergyPerMonth,
	LAG(SUM(energy_output_kwh)) OVER(ORDER BY MONTH(last_maintenance_date)) PreviousMonthEnergy,
	SUM(energy_output_kwh) - LAG(SUM(energy_output_kwh)) OVER(ORDER BY MONTH(last_maintenance_date)) MonthOverMonthGrowth,
	CASE
		WHEN SUM(energy_output_kwh) - LAG(SUM(energy_output_kwh)) OVER(ORDER BY MONTH(last_maintenance_date)) > 0 THEN 'Performed well'
		WHEN SUM(energy_output_kwh) - LAG(SUM(energy_output_kwh)) OVER(ORDER BY MONTH(last_maintenance_date)) < 0 THEN 'Performed poorly'
		WHEN SUM(energy_output_kwh) - LAG(SUM(energy_output_kwh)) OVER(ORDER BY MONTH(last_maintenance_date)) IS NULL THEN 'N/A'
		ELSE 'Same as last month'
	END Performance_Status
FROM SolarPanelMetrics
GROUP BY MONTH(last_maintenance_date)

-- 7. Compare current panel output with the previous maintenance cycle

SELECT
	panel_id,
	[model_name],
	last_maintenance_date,
	energy_output_kwh,
	LAG(energy_output_kwh) OVER(PARTITION BY last_maintenance_date ORDER BY energy_output_kwh) Comparison
FROM SolarPanelMetrics

-- 8. Determine the difference between consecutive energy readings

SELECT
	panel_id,
	[model_name],
	last_maintenance_date,
	energy_output_kwh,
	LAG(energy_output_kwh) OVER(ORDER BY panel_id) PreviousEnergyOutput,
	energy_output_kwh - LAG(energy_output_kwh) OVER(ORDER BY panel_id) EnergyDifference
FROM SolarPanelMetrics

-- 9. Find the first and last maintenance record for each panel

-- First Maintenance for each panel

SELECT *
FROM(
	SELECT 
		panel_id,
		[model_name],
		last_maintenance_date,
		DENSE_RANK() OVER (PARTITION BY [model_name] ORDER BY last_maintenance_date) FirstMaintenance
	FROM SolarPanelMetrics
)t WHERE FirstMaintenance = 1

-- Last Maintenance for each panel

SELECT *
FROM(
	SELECT 
		panel_id,
		[model_name],
		last_maintenance_date,
		DENSE_RANK() OVER (PARTITION BY [model_name] ORDER BY last_maintenance_date DESC) LastMaintenance
	FROM SolarPanelMetrics
)t	WHERE LastMaintenance = 1

-- If we want just one first and last maintenance record, we'll use the ROW_NUMBER Function

-- First maintenance date

SELECT *
FROM(
	SELECT
		panel_id,
		[model_name],
		last_maintenance_date,
		ROW_NUMBER() OVER (PARTITION BY [model_name] ORDER BY last_maintenance_date) FirstMaintenance
	FROM SolarPanelMetrics
)t WHERE FirstMaintenance = 1

-- Last maintenance date

SELECT *
FROM(
	SELECT
		panel_id,
		[model_name],
		last_maintenance_date,
		ROW_NUMBER() OVER (PARTITION BY [model_name] ORDER BY last_maintenance_date DESC) LastMaintenance
	FROM SolarPanelMetrics
)t WHERE LastMaintenance = 1

-- 10. Detect duplicate maintenance activities using row numbering

SELECT *
FROM (
	SELECT
		panel_id,
		[model_name],
		last_maintenance_date,
		ROW_NUMBER() OVER (PARTITION BY panel_id, [model_name], last_maintenance_date ORDER BY last_maintenance_date) RowNumbering
	FROM SolarPanelMetrics
)t WHERE RowNumbering > 1

-- 11. Assign performance tiers using NTILE()

SELECT
	panel_id,
	[model_name],
	energy_output_kwh,
	NTILE(3) OVER (ORDER BY energy_output_kwh DESC) PerformanceQuartile,
	CASE
		WHEN NTILE(4) OVER (ORDER BY energy_output_kwh DESC) = 1 THEN 'High'
		WHEN NTILE(4) OVER (ORDER BY energy_output_kwh DESC) = 2 THEN 'Average'
		WHEN NTILE(4) OVER (ORDER BY energy_output_kwh DESC) = 3 THEN 'Low'
	END PerformanceTiers
FROM SolarPanelMetrics

-- 12. Rank panels within each model group by efficiency

SELECT
	panel_id,
	[model_name],
	efficiency_rating,
	DENSE_RANK() OVER (PARTITION BY [model_name] ORDER BY efficiency_rating DESC) RankedPanels
FROM SolarPanelMetrics

-- 13. Find the second-highest energy-producing panel in each category

SELECT * 
FROM(
	SELECT
		panel_id,
		[model_name],
		energy_output_kwh,
		DENSE_RANK() OVER (PARTITION BY [model_name] ORDER BY energy_output_kwh DESC) EnergyProductionRank
	FROM SolarPanelMetrics
)t WHERE EnergyProductionRank = 2

--- 14. Calculate moving average energy output over 7 days

SELECT 
	panel_id,
	[model_name],
	last_maintenance_date,
	AVG(energy_output_kwh) OVER (ORDER BY last_maintenance_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) MovingAvg_7Days
FROM SolarPanelMetrics

-- 15. Compute rolling average efficiency ratings

SELECT
	panel_id,
	[model_name],
	last_maintenance_date,
	efficiency_rating,
	AVG(efficiency_rating) OVER (ORDER BY last_maintenance_date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) RollingAvg
FROM SolarPanelMetrics

-- 16. Analyse 3-month rolling maintenance trends

SELECT 
    a.panel_id,
    a.model_name,
    a.last_maintenance_date,
    a.energy_output_kwh,
    -- Counts how many maintenance events occurred for this panel in the last 3 months
    (
        SELECT COUNT(*) 
        FROM SolarPanelMetrics b
        WHERE b.panel_id = a.panel_id
          AND b.last_maintenance_date BETWEEN DATEADD(month, -3, a.last_maintenance_date) AND a.last_maintenance_date
    ) AS Maintenance_Count_Past_3Months,
    
    -- Calculates the average energy output of the panel over that 3-month maintenance window
    (
        SELECT AVG(b.energy_output_kwh) 
        FROM SolarPanelMetrics b
        WHERE b.panel_id = a.panel_id
          AND b.last_maintenance_date BETWEEN DATEADD(month, -3, a.last_maintenance_date) AND a.last_maintenance_date
    ) AS Avg_Energy_Past_3Months
FROM SolarPanelMetrics a
ORDER BY a.panel_id, a.last_maintenance_date;

-- 17. Find panels performing above the moving average

SELECT
	panel_id,
	[model_name],
	energy_output_kwh,
	efficiency_rating
FROM(
	SELECT
		panel_id,
		[model_name],
		last_maintenance_date,
		energy_output_kwh,
		efficiency_rating,
		AVG(energy_output_kwh) OVER (ORDER BY [last_maintenance_date] ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) MovingAvg
	FROM SolarPanelMetrics
)t WHERE energy_output_kwh > MovingAvg

-- 18. Detect sudden spikes or drops in energy production

SELECT
	panel_id,
	[model_name],
	energy_output_kwh,
	efficiency_rating
FROM(
	SELECT
		panel_id,
		[model_name],
		energy_output_kwh,
		efficiency_rating,
		LEAD(energy_output_kwh) OVER(PARTITION BY [model_name] ORDER BY last_maintenance_date) Spike
	FROM SolarPanelMetrics
)t WHERE energy_output_kwh < Spike 


